# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

# Change permalink theme to pretty
permalink: pretty

# Site Settings
lang: en
title: SatSchool
tagline: SatSchool
#email: your-email@domain.com
description: >
  The website for the SatSchool outreach programme
#baseurl: "/SatSchool"
#url: "https://satschool-outreach.github.io"
#permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
favicon: /img/favicon.png
footer_menu: footer-menu

google_analytics: G-GWRKPZ8HSP

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
